#debug: true
#logging:
#  level:
#    org.springframework.web: info
#    com.github.binarywang.demo.wx.miniapp: debug
#    cn.binarywang.wx.miniapp: debug
wx:
  miniapp:
    configs:
        - appid: wxb91ed27f01c09f0d
          secret: 4caa1c4c4d0d9f05706816570e1e462c
#          token: #微信小程序消息服务器配置的token
#          aesKey: #微信小程序消息服务器配置的EncodingAESKey
          msgDataFormat: JSON
