# Spring properties
spring:
  application:
    name: blockchain-service  # Identify this application
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime
#    prefix: classpath:/blockchain-server/templates/    # Trailing / mandatory
                       # Template location for this application only

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
#  1. Define URL of registration server (defaultZone)
#  2. Reduce lease-renewal time so processes register more quickly
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port
# Web3J
web3j:
# An infura endpoint
  client-address : https://rinkeby.infura.io/udBxuyCvHOqvmFhEEi4S
# Or, an IPC endpoing
#  client-address :  /path/to/file.ipc
  admin-client : true
#This sets all three OkHttp3 timeouts: connect, read, and write.
#Valid values are any non-negative integer.A value of '0' means: no timeout.
#Note: This is not required for transacting with web3j.
  httpTimeoutSeconds : 600